[2022-08-20 10:24:11,242] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.import_rates scheduled__2022-08-20T06:00:00+00:00 [queued]>
[2022-08-20 10:24:11,967] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.import_rates scheduled__2022-08-20T06:00:00+00:00 [queued]>
[2022-08-20 10:24:11,978] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-20 10:24:11,984] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-20 10:24:11,993] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-20 10:24:12,871] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): import_rates> on 2022-08-20 06:00:00+00:00
[2022-08-20 10:24:13,128] {standard_task_runner.py:52} INFO - Started process 4717 to run task
[2022-08-20 10:24:13,379] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'yandex-rates-test', 'import_rates', 'scheduled__2022-08-20T06:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/yandex_dag.py', '--cfg-path', '/tmp/tmpfcb10fdb', '--error-file', '/tmp/tmp8igkq5a2']
[2022-08-20 10:24:13,459] {standard_task_runner.py:80} INFO - Job 41: Subtask import_rates
[2022-08-20 10:24:16,041] {task_command.py:371} INFO - Running <TaskInstance: yandex-rates-test.import_rates scheduled__2022-08-20T06:00:00+00:00 [running]> on host 00f41d9230c6
[2022-08-20 10:24:21,202] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yandex-rates-test
AIRFLOW_CTX_TASK_ID=import_rates
AIRFLOW_CTX_EXECUTION_DATE=2022-08-20T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-20T06:00:00+00:00
[2022-08-20 10:24:23,254] {python.py:173} INFO - Done. Returned value was: None
[2022-08-20 10:24:23,980] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=yandex-rates-test, task_id=import_rates, execution_date=20220820T060000, start_date=20220820T102411, end_date=20220820T102423
[2022-08-20 10:24:25,042] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-08-20 10:24:25,175] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 4717. PIDs of all processes in the group: [4717]
[2022-08-20 10:24:25,179] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 4717
[2022-08-20 10:24:25,204] {process_utils.py:75} INFO - Process psutil.Process(pid=4717, status='terminated', exitcode=0, started='10:24:12') (4717) terminated with exit code 0
