[2022-11-05 15:18:19,398] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-11-05T15:17:53.726801+00:00 [queued]>
[2022-11-05 15:18:19,815] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-11-05T15:17:53.726801+00:00 [queued]>
[2022-11-05 15:18:19,817] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-05 15:18:19,820] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-11-05 15:18:19,849] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-05 15:18:20,389] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): also_run_this> on 2022-11-05 15:17:53.726801+00:00
[2022-11-05 15:18:20,558] {standard_task_runner.py:52} INFO - Started process 3110 to run task
[2022-11-05 15:18:20,691] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'also_run_this', 'manual__2022-11-05T15:17:53.726801+00:00', '--job-id', '19', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpgg4imzkq', '--error-file', '/tmp/tmpu_p6j9q9']
[2022-11-05 15:18:20,694] {standard_task_runner.py:80} INFO - Job 19: Subtask also_run_this
[2022-11-05 15:18:23,782] {task_command.py:371} INFO - Running <TaskInstance: example_bash_operator.also_run_this manual__2022-11-05T15:17:53.726801+00:00 [running]> on host ec0dc6e942fe
[2022-11-05 15:18:26,478] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-11-05T15:17:53.726801+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-05T15:17:53.726801+00:00
[2022-11-05 15:18:26,501] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-05 15:18:26,509] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "run_id=manual__2022-11-05T15:17:53.726801+00:00 | dag_run=<DagRun example_bash_operator @ 2022-11-05 15:17:53.726801+00:00: manual__2022-11-05T15:17:53.726801+00:00, externally triggered: True>"']
[2022-11-05 15:18:26,792] {subprocess.py:85} INFO - Output:
[2022-11-05 15:18:26,825] {subprocess.py:92} INFO - run_id=manual__2022-11-05T15:17:53.726801+00:00 | dag_run=<DagRun example_bash_operator @ 2022-11-05 15:17:53.726801+00:00: manual__2022-11-05T15:17:53.726801+00:00, externally triggered: True>
[2022-11-05 15:18:26,874] {subprocess.py:96} INFO - Command exited with return code 0
[2022-11-05 15:18:28,246] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20221105T151753, start_date=20221105T151819, end_date=20221105T151828
[2022-11-05 15:18:28,804] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-05 15:18:29,456] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
