[2022-08-16 14:18:08,388] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.insert_data scheduled__2022-08-16T09:00:00+00:00 [failed]>
[2022-08-16 14:18:08,401] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.insert_data scheduled__2022-08-16T09:00:00+00:00 [failed]>
[2022-08-16 14:18:08,403] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-16 14:18:08,405] {taskinstance.py:1377} INFO - Starting attempt 4 of 2
[2022-08-16 14:18:08,408] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-16 14:18:08,519] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): insert_data> on 2022-08-16 09:00:00+00:00
[2022-08-16 14:18:08,565] {standard_task_runner.py:52} INFO - Started process 4056 to run task
[2022-08-16 14:18:08,579] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'yandex-rates-test', 'insert_data', 'scheduled__2022-08-16T09:00:00+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/yandex_dag.py', '--cfg-path', '/tmp/tmp780rt3jg', '--error-file', '/tmp/tmpbnp8dcro']
[2022-08-16 14:18:08,584] {standard_task_runner.py:80} INFO - Job 7: Subtask insert_data
[2022-08-16 14:18:08,748] {task_command.py:371} INFO - Running <TaskInstance: yandex-rates-test.insert_data scheduled__2022-08-16T09:00:00+00:00 [running]> on host b232b3e4166c
[2022-08-16 14:18:08,946] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yandex-rates-test
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-16T09:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-16T09:00:00+00:00
[2022-08-16 14:18:08,997] {logging_mixin.py:115} INFO - rate_date:  2022-08-16
[2022-08-16 14:18:09,002] {logging_mixin.py:115} INFO - value_:  24207.92857100000037
[2022-08-16 14:18:09,034] {base.py:68} INFO - Using connection ID 'postgre_test_db' for task execution.
[2022-08-16 14:18:09,109] {python.py:173} INFO - Done. Returned value was: None
[2022-08-16 14:18:09,153] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=yandex-rates-test, task_id=insert_data, execution_date=20220816T090000, start_date=20220816T141808, end_date=20220816T141809
[2022-08-16 14:18:09,279] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-16 14:18:09,514] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
