[2022-08-23 12:00:09,099] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-23T09:00:00+00:00 [queued]>
[2022-08-23 12:00:09,162] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-23T09:00:00+00:00 [queued]>
[2022-08-23 12:00:09,163] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 12:00:09,165] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-23 12:00:09,168] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 12:00:09,238] {taskinstance.py:1397} INFO - Executing <Task(FileSensor): waiting_for_file> on 2022-08-23 09:00:00+00:00
[2022-08-23 12:00:09,250] {standard_task_runner.py:52} INFO - Started process 9960 to run task
[2022-08-23 12:00:09,260] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'yandex-rates-test', 'waiting_for_file', 'scheduled__2022-08-23T09:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/yandex_dag.py', '--cfg-path', '/tmp/tmp7tmpgz1m', '--error-file', '/tmp/tmp3cpqwfp7']
[2022-08-23 12:00:09,261] {standard_task_runner.py:80} INFO - Job 61: Subtask waiting_for_file
[2022-08-23 12:00:09,390] {task_command.py:371} INFO - Running <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-23T09:00:00+00:00 [running]> on host 00f41d9230c6
[2022-08-23 12:00:09,599] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yandex-rates-test
AIRFLOW_CTX_TASK_ID=waiting_for_file
AIRFLOW_CTX_EXECUTION_DATE=2022-08-23T09:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-23T09:00:00+00:00
[2022-08-23 12:00:09,657] {base.py:68} INFO - Using connection ID 'ya_***_workshop_file_path' for task execution.
[2022-08-23 12:00:09,659] {filesystem.py:58} INFO - Poking for file C:/Users/AbduevSA-LA/Desktop/Yandex/Airflow_workshop/workshop_***-main/
[2022-08-23 12:00:09,737] {taskinstance.py:1873} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2022-08-23 12:00:09,896] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-23 12:00:10,205] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-23 12:02:11,860] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-23T09:00:00+00:00 [queued]>
[2022-08-23 12:02:12,056] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-23T09:00:00+00:00 [queued]>
[2022-08-23 12:02:12,057] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 12:02:12,058] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-23 12:02:12,060] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 12:02:12,300] {taskinstance.py:1397} INFO - Executing <Task(FileSensor): waiting_for_file> on 2022-08-23 09:00:00+00:00
[2022-08-23 12:02:12,340] {standard_task_runner.py:52} INFO - Started process 10049 to run task
[2022-08-23 12:02:12,378] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'yandex-rates-test', 'waiting_for_file', 'scheduled__2022-08-23T09:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/yandex_dag.py', '--cfg-path', '/tmp/tmpx__ql8pv', '--error-file', '/tmp/tmpb9hsjj34']
[2022-08-23 12:02:12,381] {standard_task_runner.py:80} INFO - Job 62: Subtask waiting_for_file
[2022-08-23 12:02:12,814] {task_command.py:371} INFO - Running <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-23T09:00:00+00:00 [running]> on host 00f41d9230c6
[2022-08-23 12:02:13,655] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yandex-rates-test
AIRFLOW_CTX_TASK_ID=waiting_for_file
AIRFLOW_CTX_EXECUTION_DATE=2022-08-23T09:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-23T09:00:00+00:00
[2022-08-23 12:02:13,810] {base.py:68} INFO - Using connection ID 'ya_***_workshop_file_path' for task execution.
[2022-08-23 12:02:13,811] {filesystem.py:58} INFO - Poking for file C:/Users/AbduevSA-LA/Desktop/Yandex/Airflow_workshop/workshop_***-main/
[2022-08-23 12:02:13,822] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 288, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: yandex-rates-test
[2022-08-23 12:02:13,860] {taskinstance.py:1420} INFO - Immediate failure requested. Marking task as FAILED. dag_id=yandex-rates-test, task_id=waiting_for_file, execution_date=20220823T090000, start_date=20220823T120211, end_date=20220823T120213
[2022-08-23 12:02:13,895] {standard_task_runner.py:97} ERROR - Failed to execute job 62 for task waiting_for_file (Snap. Time is OUT. DAG id: yandex-rates-test; 10049)
[2022-08-23 12:02:13,993] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-23 12:02:14,151] {logging_mixin.py:115} INFO - {'conf': <***.configuration.AirflowConfigParser object at 0x7fdb0783b690>, 'dag': <DAG: yandex-rates-test>, 'dag_run': <DagRun yandex-rates-test @ 2022-08-23 09:00:00+00:00: scheduled__2022-08-23T09:00:00+00:00, externally triggered: False>, 'data_interval_end': DateTime(2022, 8, 23, 12, 0, 0, tzinfo=Timezone('UTC')), 'data_interval_start': DateTime(2022, 8, 23, 9, 0, 0, tzinfo=Timezone('UTC')), 'ds': '2022-08-23', 'ds_nodash': '20220823', 'execution_date': DateTime(2022, 8, 23, 9, 0, 0, tzinfo=Timezone('UTC')), 'inlets': [], 'logical_date': DateTime(2022, 8, 23, 9, 0, 0, tzinfo=Timezone('UTC')), 'macros': <module '***.macros' from '/home/***/.local/lib/python3.7/site-packages/***/macros/__init__.py'>, 'next_ds': '2022-08-23', 'next_ds_nodash': '20220823', 'next_execution_date': DateTime(2022, 8, 23, 12, 0, 0, tzinfo=Timezone('UTC')), 'outlets': [], 'params': {}, 'prev_data_interval_start_success': None, 'prev_data_interval_end_success': None, 'prev_ds': '2022-08-23', 'prev_ds_nodash': '20220823', 'prev_execution_date': DateTime(2022, 8, 23, 6, 0, 0, tzinfo=Timezone('UTC')), 'prev_execution_date_success': None, 'prev_start_date_success': None, 'run_id': 'scheduled__2022-08-23T09:00:00+00:00', 'task': <Task(FileSensor): waiting_for_file>, 'task_instance': <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-23T09:00:00+00:00 [failed]>, 'task_instance_key_str': 'yandex-rates-test__waiting_for_file__20220823', 'test_mode': False, 'ti': <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-23T09:00:00+00:00 [failed]>, 'tomorrow_ds': '2022-08-24', 'tomorrow_ds_nodash': '20220824', 'ts': '2022-08-23T09:00:00+00:00', 'ts_nodash': '20220823T090000', 'ts_nodash_with_tz': '20220823T090000+0000', 'var': {'json': None, 'value': None}, 'conn': None, 'yesterday_ds': '2022-08-22', 'yesterday_ds_nodash': '20220822', 'exception': AirflowSensorTimeout('Snap. Time is OUT. DAG id: yandex-rates-test')}
[2022-08-23 12:02:14,159] {logging_mixin.py:115} INFO - Sensor timed out
[2022-08-23 12:02:14,276] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
